-- MySQL Script generated by MySQL Workbench
-- dom 19 mar 2023 19:16:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`bills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bills` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `insert_date` DATETIME NULL,
  `project_id` INT NOT NULL,
  `description` TEXT NULL,
  `created_by_user_id` INT NOT NULL,
  `type` ENUM('deposit', 'payment') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_bills_projects1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_bills_users1_idx` (`created_by_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_bills_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bills_users1`
    FOREIGN KEY (`created_by_user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idclients_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`documents` ;

CREATE TABLE IF NOT EXISTS `mydb`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` ENUM('informed_consent', 'parental_leave', 'national_id') NOT NULL,
  `uuid` INT NOT NULL,
  `projects_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_documents_projects1_idx` (`projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_documents_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `mydb`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `insert_date` DATETIME NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `period` VARCHAR(45) NULL,
  `project_id` INT NULL,
  `studio_id` INT NULL,
  `inserted_by_user_id` INT NOT NULL,
  `visibility` ENUM('user', 'studio', 'public') NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_events_studios1_idx` (`studio_id` ASC) VISIBLE,
  INDEX `fk_events_users1_idx` (`inserted_by_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_events_studios1`
    FOREIGN KEY (`studio_id`)
    REFERENCES `mydb`.`studios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`inserted_by_user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`images` ;

CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `id` INT NOT NULL,
  `uuid` VARCHAR(45) NOT NULL,
  `created_by_user_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_users1_idx` (`created_by_user_id` ASC) VISIBLE,
  INDEX `fk_images_projects1_idx` (`projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_users1`
    FOREIGN KEY (`created_by_user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `mydb`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`projects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `studio_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_projects_studios1_idx` (`studio_id` ASC) VISIBLE,
  INDEX `fk_projects_clients1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_projects_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_studios1`
    FOREIGN KEY (`studio_id`)
    REFERENCES `mydb`.`studios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`project_sessions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`project_sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projects_id` INT NOT NULL,
  `events_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_project_sessions_projects1_idx` (`projects_id` ASC) VISIBLE,
  INDEX `fk_project_sessions_events1_idx` (`events_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_sessions_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `mydb`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_sessions_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `mydb`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`studios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`studios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`studios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` ENUM('private', 'collective') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idstudios_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `privileges` ENUM('admin', 'user') NOT NULL,
  `second_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `validation_code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusers_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_has_clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_has_clients` (
  `users_id` INT NOT NULL,
  `clients_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `visibility` ENUM('user', 'studio', 'public') NULL,
  INDEX `fk_users_has_clients_clients1_idx` (`clients_id` ASC) VISIBLE,
  INDEX `fk_users_has_clients_users1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_clients_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_clients_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `mydb`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_studios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_has_studios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_has_studios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `studios_id` INT NOT NULL,
  `relation` ENUM('owner', 'resident', 'guest') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_studios_studios1_idx` (`studios_id` ASC) VISIBLE,
  INDEX `fk_users_has_studios_users_idx` (`users_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_studios_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_studios_studios1`
    FOREIGN KEY (`studios_id`)
    REFERENCES `mydb`.`studios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
